name: chronochroma
description: Time flies, colors fades...

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flame: ^1.5.0
  flutter:
    sdk: flutter
  very_good_analysis: ^3.1.0
  cupertino_icons: ^1.0.5
  flame_tiled: ^1.9.0
  flame_forge2d: ^0.12.4
  url_launcher: ^6.0.9
  themed: ^4.0.0
  shared_preferences: ^2.0.17
  http: ^0.13.5
  connectivity_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/joystick_background.png
    - assets/images/joystick_knob.png
    - assets/images/grass/
    - assets/images/character/
    - assets/images/icon/
    - assets/audio/
    - assets/tiles/
    - assets/images/upgrades/
    - assets/images/idle.gif
    - assets/images/character/32x32-bat-sprite.png
    - assets/images/arrow.png
    - assets/images/gameOver.png
    - assets/images/logoMEILLEUREVER.png
    - assets/images/button_quitter.png
    - assets/images/button_rejouer.png
    - assets/images/button_jouer.png
    - assets/images/button_ameliorations.png
    - assets/images/button_scores.png
    - assets/images/button_commencer.png
    - assets/images/skeleton/
    - assets/images/avatar.png
    - assets/images/upgrades/atk.png
    - assets/images/upgrades/health.png
    - assets/images/upgrades/speed.png
    - assets/images/upgrades/vision.png
    - assets/images/upgrades/background.png
    - assets/images/FireTrap.png

