name: chronochroma
description: Time flies, colors fades...

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flame: ^1.5.0
  flutter:
    sdk: flutter
  very_good_analysis: ^3.1.0
  cupertino_icons: ^1.0.5
  flame_tiled: ^1.9.0
  flame_forge2d: ^0.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/joystick_background.png
    - assets/images/joystick_knob.png
    - assets/images/knight_idle_spritesheet.png
    - assets/images/knight_walk_left_spritesheet.png
    - assets/images/knight_walk_right_spritesheet.png
    - assets/images/grass/
    - assets/audio/
    - assets/tiles/
